# Generated by Django 5.2.8 on 2025-12-01 01:50

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_perfilpcd_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useravatar',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Avatar de Usuário', 'verbose_name_plural': 'Avatares de Usuário'},
        ),
        migrations.RemoveIndex(
            model_name='useravatar',
            name='account_use_user_id_ecfa5c_idx',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='curriculo',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='deficiencias',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='laudo_medico',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='perfilpcd',
            name='uf',
        ),
        migrations.AlterUniqueTogether(
            name='useravatar',
            unique_together={('user', 'is_atual')},
        ),
        migrations.AlterField(
            model_name='perfilmedico',
            name='crm',
            field=models.CharField(max_length=15, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='perfilpcd',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='perfilpcd',
            name='percentual_perfil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfilpcd',
            name='status_medico',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status Médico'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='imagem',
            field=models.ImageField(help_text='Formatos aceitos: JPG, PNG, WEBP.', max_length=500, upload_to=account.models.avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem do Avatar'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='is_atual',
            field=models.BooleanField(default=True, verbose_name='Avatar atual'),
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='largura',
        ),
    ]
