# Generated by Django 5.2.8 on 2025-12-01 02:22

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_especialidade_options_alter_useravatar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recurso de Acessibilidade',
                'verbose_name_plural': 'Recursos de Acessibilidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado'), ('em_analise', 'Em Análise'), ('pre_selecionado', 'Pré-selecionado'), ('entrevista_agendada', 'Entrevista Agendada'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('desistente', 'Desistente')], db_index=True, default='pendente', max_length=30)),
                ('mensagem_candidato', models.TextField(blank=True)),
                ('avaliacao_empresa', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observacoes_empresa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pcd', models.ForeignKey(limit_choices_to={'tipo': 'pcd'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='job_vacancies.candidatura')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente_tipo', models.CharField(choices=[('empresa', 'Empresa'), ('pcd', 'PCD')], max_length=10)),
                ('conteudo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chat_anexos/%Y/%m/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_por_empresa', models.BooleanField(default=False)),
                ('lida_por_pcd', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='job_vacancies.conversa')),
            ],
            options={
                'ordering': ['enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('emprego', 'Emprego'), ('capacitacao', 'Capacitação')], default='emprego', max_length=20)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mostrar_salario', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_aprovacao', 'Aguardando Aprovação Médica'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('aberta', 'Aberta'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], db_index=True, default='rascunho', max_length=30)),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
                ('recursos_disponiveis', models.ManyToManyField(blank=True, to='job_vacancies.recursoacessibilidade')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='job_vacancies.vaga'),
        ),
        migrations.CreateModel(
            name='AvaliacaoVagaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('ajustes_necessarios', 'Ajustes Necessários')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('ajustes_recomendados', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('deficiencias_elegiveis', models.ManyToManyField(blank=True, to='account.categoriadeficiencia')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_medicas', to='job_vacancies.vaga')),
            ],
            options={
                'verbose_name': 'Avaliação Médica da Vaga',
                'ordering': ['-avaliado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['status'], name='job_vacanci_status_86eed0_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['empresa', 'status'], name='job_vacanci_empresa_ffc7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titulo', 'descricao'], name='job_vacanci_titulo_874ae9_gin'),
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['status'], name='job_vacanci_status_cc604a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['vaga', 'status'], name='job_vacanci_vaga_id_9aa77b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('vaga', 'pcd')},
        ),
    ]
